version: '2'
services:
  sonarqube:
    labels:
      io.rancher.container.hostname_override: container_name
    image: sonarqube:6.5-alpine
    links:
        - db:db
    environment:
        SONARQUBE_JDBC_USERNAME: ${postgres_user}
        SONARQUBE_JDBC_PASSWORD: ${postgres_password}
        SONARQUBE_JDBC_URL: jdbc:postgresql://db:${postgres_port}/${postgres_db}
    labels:
        io.rancher.container.hostname_override: container_name
    volumes:
        - sonarqube-data:/opt/sonarqube/extensions/plugins
  sonarqube-lb:
    image: rancher/lb-service-haproxy:v0.6.4
    ports:
      - ${http_port}:${http_port}
  sonarqube-db:
    labels:
      io.rancher.container.hostname_override: container_name
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_USER:  ${postgres_user}
      POSTGRES_PASSWORD:  ${postgres_password}
      POSTGRES_DB:  ${postgres_db}
    volumes:
      - db-data:/var/lib/postgresql
volumes:
  db-data:
    driver: local
  sonarqube-data:
    driver: local

