version: '2'

services:
  postgres:
    image: postgres:9.5
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      http_proxy: ds
      https_proxy: ds
  huginn-web:
    image: huginn/huginn-single-process:fc1daf8b91398929cedd72895cc95647e3ed7b6a
    restart: always
    external_links:
      - postgres: postgres
volumes:
  postgres-data:
    driver: ${STORAGE_DRIVER}
