version: '2'

catalog:
  name: "Artifactory OSS"
  version: "5.4.4"
  description: "Artifactory is a universal Binary Repository Manager"
  questions:
    - variable: "PUBLISH_PORT"
      label: "Publish port"
      description: |
        Set port if you want publish external port for Artifactory server.
      required: false
      type: "string"
      default: "8081"
    - variable: "EXTRA_JAVA_OPTIONS"
      label: "Extra Java options"
      description: |
      type: "string"
      default: ""
    - variable: "VOLUME_DRIVER"
      type: "string"
      label: "Volume driver for Artifactory data"
      description: |
        Specifiy docker volume driver to use
      default: "local"
      required: true
