version: '2'
services:
  gogs:
    image: gogs/gogs:0.11.19
    ports:
      - ${http_port}:3000
      - ${ssh_port}:22
    links:
      - mysql:db
    volumes:
      - gogs-data:/data/gogs
  mysql:
    image: mysql:5.5
    ports:
      - ${public_port}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_password}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
      MYSQL_DATABASE: ${mysql_db}
    volumes:
      - gogs-db:/var/lib/mysql
volumes:
  gogs-db:
    driver: ${volume_driver}
  gogs-data:
    driver: ${volume_driver}

