.catalog:
  name: "Bamboo"
  version: "5.15.3"
  description: "Bambo Server"
  uuid: bamboo-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: lb_http_port
      description: "HTTP port to access Bamboo Server UI"
      label: "Bamboo LB HTTP Port"
      required: true
      default: 80
      type: "int"
    - variable: scale
      description: "Number of Bamboo Agents"
      label: "Number of Bamboo Agents"
      required: true
      default: 1
      type: "int"
    - variable: packages
      description: "List of additional packages which should be installed on Bamboo Agent. Put pakcages separated with space."
      label: "(EXPERIMENTAL) Packages to install on Agent."
      required: false
      default: ""
      type: "string"
    - variable: postgres_db
      description: "Postgres Database"
      label: "Postgres Database"
      required: true
      default: "bamboo"
      type: "string"
    - variable: postgres_user
      description: "Postgres User"
      label: "Postgres User"
      required: true
      default: "bamboo"
      type: "string"
    - variable: postgres_password
      description: "Postgres Password"
      label: "Postgres Password"
      required: true
      default: "bamboo"
      type: "string"
    - variable: http_proxy
      description: "In case you are at corporate network, setup http_proxy variable"
      label: "http_proxy"
      required: false
      default: ""
      type: "string"
    - variable: https_proxy
      description: "In case you are at corporate network, setup https_proxy variable"
      label: "https_proxy"
      required: false
      default: ""
      type: "string"
      
version: '2'
services:
  bamboo-server-lb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: bamboo-server
        source_port: ${lb_http_port}
        target_port: 8085
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  bamboo-server:
    scale: 1
    retain_ip: true
    health_check:
      port: 8085
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  bamboo-agent:
    scale: ${scale}
    retain_ip: true
