apiVersion: v1
kind: ReplicationController
metadata: 
  name: "zookeeper"
  namespace: "default"
  labels:
    provider: "zookeeper"
    name: "zookeeper"
spec:
  replicas: 2
  selector:
    provider: "zookeeper"
    name: "zookeeper"
  template:
    metadata: 
      labels:
        provider: "zookeeper"
        name: "zookeeper"
    spec:
      containers:
        - name: "zk-conf"
          image: "rawmind/k8s-zk:3.4.8"
          volumeMounts:
            - mountPath: "/opt/tools"
              name: "zk-conf"
          ports: 
          resources:
            cpu: "10m"
            memory: "4Mi"
          imagePullPolicy: "IfNotPresent"
        - name: "zk-service"
          image: "rawmind/alpine-zk:3.4.8-12"
          env:
            - name: JVMFLAGS
              value: "-Xmx${zk_mem}m -Xms${zk_mem}m"
            - name: ZK_DATA_DIR
              value: "${zk_data_dir}"
            - name: ZK_INIT_LIMIT
              value: "${zk_init_limit}"
            - name: ZK_MAX_CLIENT_CXNS
              value: "${zk_max_client_cxns}"
            - name: ZK_SYNC_LIMIT
              value: "${zk_sync_limit}"
            - name: ZK_TICK_TIME
              value: "${zk_tick_time}"
          volumeMounts:
            - mountPath: "${zk_data_dir}"
              name: "zk-data"
            - mountPath: "/opt/tools"
              name: "zk-conf"
          ports:
            - containerPort: 2181
              name: "zk-client"
              protocol: "TCP"
            - containerPort: 2888
              name: "zk-server"
              protocol: "TCP"
            - containerPort: 3888
              name: "zk-leader"
              protocol: "TCP"
          resources:
            cpu: "1000m"
            memory: "${zk_mem}Mi"
          imagePullPolicy: "IfNotPresent"
      restartPolicy: "Always"
      volumes:
        - name: "zk-data"
          emptyDir: {}
        - name: "zk-conf"
          emptyDir: {}