apiVersion: v1
kind: Service
metadata:
  name: "zookeeper"
  labels:
    name: "zookeeper"
spec:
  ports:
  - port: 2181
    targetPort: 2181
    name: "zk-client"
    protocol: "TCP"
  - port: 2888
    targetPort: 2888
    name: "zk-server"
    protocol: "TCP"
  - port: 3888
    targetPort: 3888
    name: "zk-lead"
    protocol: "TCP"
  selector:
    name: "zookeeper"
