name: "Weave Cloud Suite"
description: |
  All you need to implement Continuous Delivery with hosted Prometheus monitoring and visual distributed system analysis/debug tools
version: "latest"
category: Continuous Delivery, Monitoring & Visualization
maintainer: "Ilya Dmitrichenko <ilya@weave.works>"
