version: 2
catalog:
  name: Drone
  version: 0.5.0
  upgrade_from: 0.5.0
  description: |
    Drone CI Server ref http://readme.drone.io/admin/installation-guide/
  questions:
    - variable: drone_open
      label: Open registration
      description: |
        Are users able to self register
      required: true
      default: true
      type: boolean
    - variable: host_port
      label: Drone server Host Port
      description: |
        Port that will be exposed on service creation
      required: true
      default: 80
      type: int
    - variable: agent_scale
      label: Drone agent scale
      description: Drone agent scale to deploy
      required: true
      default: 1
      type: int
    - variable: drone_secret
      label: Secret to be used between the server and agents
      description: Enter the Secret to be used
      type: password
      required: true
    - variable: drone_admins
      label: Drone Admins
      description: List of admins for drone coma seperated
      type: string
      required: true
    - variable: drone_orgs
      label: Organizations
      description: Comman seperated list of org that can access drone
      type: string
      required: false
    - variable: "drone_driver"
      type: "enum"
      required: true
      label: "Remote Driver"
      description: "Remote Git and Auth scheme. ref http://readme.drone.io/admin"
      options:
        - github
        - bitbucket
        - gitlab
        - gogs
    - variable: drone_driver_client
      label: Remote Driver client
      description: client key from remote driver
      type: string
      required: false
    - variable: drone_driver_secret
      label: Remote Driver secret
      description: secret key from remote driver
      type: string
      required: false
    - variable: drone_driver_url
      label: Remote Driver url
      description: "Remote Driver server url. Required for gitlab and gogs, http://readme.drone.io/admin"
      type: string
      required: false
    - variable: database_driver
      label: Database Driver
      description: What database to use (will use sqlite by default mounted at -/var/lib/drone/)
      type: enum
      default: "sqlite3"
      options:
        - "sqlite3"
        - "mysql"
        - "postgres"
      required: true
    - variable: "database_service"
      type: "service"
      label: "Database Service"
      description: "Service to link to for database. For instance if using the default Rancher Galera cluster select galera/galera-lb."
      required: false
services:
  agent:
    scale: ${agent_scale}
    start_on_create: true
  server:
    scale: 1
    start_on_create: true
    health_check:
      port: 8000
      interval: 2000
      unhealthy_threshold: 3
      strategy: recreate
      request_line: GET / HTTP/1.0
      healthy_threshold: 2
      response_timeout: 2000
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: server
        source_port: ${host_port}
        target_port: 8000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate